#!/usr/bin/env python3
"""Regenerate the ISA/API inventory from AMD's machine-readable XML.

Usage: python3 tools/isa_inventory.py /path/to/machine-readable-isa/isa
The table is an inventory, not a claim that existing APIs match both targets.
"""
import collections
import hashlib
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
isa_dir = Path(sys.argv[1])
apis = set(re.findall(r"int goc_(\w+)\(", (root / "include/goc/detail/goc_instructions.h").read_text()))
instructions = {}
sources = []
for arch in (3, 4):
    path = isa_dir / f"amdgpu_isa_rdna{arch}.xml"
    sources.append(f"- `{path.name}`: SHA-256 `{hashlib.sha256(path.read_bytes()).hexdigest()}`")
    entries = ET.parse(path).findall(".//Instructions/Instruction")
    instructions[arch] = {e.findtext("InstructionName").lower(): e for e in entries}
    assert len(instructions[arch]) == len(entries), "duplicate canonical mnemonic"

# These use the data-share encoding but only route register values, with no LDS access.
register_routing = {"ds_bpermute_fi_b32", "ds_swizzle_b32", "ds_bpermute_b32", "ds_permute_b32",
                    "ds_permute_b64", "ds_bpermute_b64"}
outside = {"VMEM", "SMEM", "EXPORT", "BRANCH", "MESSAGE", "TRAP", "WAVE_CONTROL"}
rows = []
counts = collections.Counter()
for name in sorted(set(instructions[3]) | set(instructions[4])):
    entries = [instructions[a][name] for a in (3, 4) if name in instructions[a]]
    groups = {e.findtext("FunctionalGroup/Name") for e in entries}
    if name in register_routing:
        scope = "in: register routing"
    elif groups <= outside:
        scope = "out: " + "/".join(sorted(groups))
    elif groups <= {"VALU", "SALU"}:
        scope = "in"
    else:
        scope = "review: " + "/".join(sorted(groups))
    # Encodings of scheduling/control operations can occur in SALU/VALU groups.
    if scope == "in" and (name.startswith(("s_wait", "s_setreg", "s_getreg", "s_movrel", "v_movrel"))
                           or name in {"s_nop", "v_nop", "s_version", "v_pipeflush"}):
        scope = "review: control/register boundary"
    # FunctionalGroup alone is insufficient: SALU includes indirect branches,
    # and the RDNA3 LDS direct loads are labeled VALU in this XML revision.
    if any(e.findtext("InstructionFlags/IsBranch") == "TRUE" or
           e.findtext("InstructionFlags/IsProgramTerminator") == "TRUE" for e in entries):
        scope = "out: branch/termination"
    elif name in {"lds_direct_load", "lds_param_load"}:
        scope = "out: LDS memory access"
    elif name in {"s_alloc_vgpr", "s_sleep_var"}:
        scope = "out: resource allocation/scheduling"
    elif name in {"v_nop", "v_pipeflush"}:
        scope = "out: pipeline scheduling"
    elif name.startswith(("s_getreg", "s_setreg", "s_movrel", "v_movrel")):
        scope = "in: register access"
    aliases = sorted({a.text.lower() for e in entries
                      for a in e.findall("AliasedInstructionNames/*")})
    alias_text = ", ".join(f"`{a}`" for a in aliases) or "—"
    symbols = []
    for suffix in ("", "_wave64", "_rdna4", "_rdna4_wave64"):
        if name + suffix in apis:
            symbols.append(f"`goc_{name + suffix}`")
    status = "API present; semantic audit pending" if symbols else "missing API"
    if scope.startswith("out:"):
        status = "excluded: memory/control/scheduling"
    counts[(scope.split(":")[0], bool(symbols))] += 1
    rows.append(f"| `{name}` | {'yes' if name in instructions[3] else '—'} | "
                f"{'yes' if name in instructions[4] else '—'} | {scope} | "
                f"{'<br>'.join(symbols) or '—'} | {alias_text} | {status} |")

text = """# RDNA3/RDNA4 ISA inventory

Generated by `tools/isa_inventory.py`. Every canonical mnemonic in both XML
specifications is listed, including exclusions. Alias spellings in XML are not
separate instructions. API presence is **not** semantic verification, bit-exact
coverage, modifier coverage, global-state support, or SIMD coverage. These gates
are tracked in [COVERAGE.md](COVERAGE.md). Do not infer architecture compatibility
from equal mnemonics or descriptions. Boundary rows remain open until reviewed; resolved scope decisions are recorded there.

Memory operations, exports, branches, messages, traps, and scheduling are outside
GoC's arithmetic/register-operation scope. Register-only data-share permutations
are included. SALU/VALU register/control boundaries are not silently excluded. Explicit branch
flags and reviewed memory/scheduling descriptions override misleading group labels.
Relative register addressing and hardware-register access remain in scope.

## Source fingerprints

""" + "\n".join(sources) + "\n\n"
text += f"RDNA3: {len(instructions[3])} canonical instructions; RDNA4: {len(instructions[4])}.\n\n"
for (scope, present), count in sorted(counts.items()):
    text += f"- {scope}, API {'present' if present else 'absent'}: {count}\n"
text += "\n| Mnemonic | RDNA3 | RDNA4 | Scope | APIs | XML aliases | Audit status |\n|---|---|---|---|---|---|---|\n"
(root / "ISA_INVENTORY.md").write_text(text + "\n".join(rows) + "\n")
print('\n'.join(text.splitlines()[16:28]))
